api:
  key: SUA-CHAVE
  url: https://cds.climate.copernicus.eu/api
area:
  bbox_stac:
  - -52.7
  - -28.5
  - -52.2
  - -28.0
  east: -52.2
  north: -28.0
  south: -28.5
  west: -52.7
period:
  end: '2025-09-30'
  start: '2025-04-01'
processing:
  cloud_cover_max: 50
  target_crs: EPSG:4326
  target_resolution: 0.001
